---

  - hosts: localhost
    connection: local
    gather_facts: False
    tags: provision
    roles:
      - ec2

    tasks:
      - name: Launch instance
        ec2:
          key_name: "{{ keypair }}"
          region: "{{ region }}"
          zone: "{{ az }}"
          image: "{{ ami_image }}"
          instance_type: "{{ instance_type }}"
          vpc_subnet_id: "{{ vpc_subnet_id }}"
          assign_public_ip: true
          group_id: "{{ security_group_name }}"
          exact_count: 1
          source_dest_check: no
          count_tag:
            Name: "{{ item.hostname }}"
          instance_tags:
              Name: "{{ item.hostname }}"
              role: "{{ item.role }}"
              environment: "{{ item.environment }}"
          volumes:
            - device_name: /dev/sda1
              volume_size: 16
              device_type: gp2
              delete_on_termination: True
          wait: true
          instance_profile_name: "{{ instance_profile_name }}"
          user_data: "{{ lookup('template', 'roles/ec2/templates/user_data_route53.j2') }}"
        with_items:
          - hostname: "{{ remote_hostname }}"
            fqdn: "aws-us-east-1a-{{ remote_hostname }}"
            role: "webserver"
            environment: "production"
        register: ec2